### ISSUE TITLE
Config and publishing stubs

### ISSUE THREAD

**Issue by markcameron** [bpocallaghan/generators#1]
I can't publish the config file using `php artisan vendor:publish`, nor does it publish the stubs. Is there specific way of doing this, or will you implement the `publishes()` method in the service provider to automatically export them?

Thanks

**Comment by bpocallaghan** [comment]
Hi Mark.

Currently you have to use `php artisan generate:publish-stubs` to publish the stubs.
[Readme](https://github.com/bpocallaghan/generators#configuration)
Please let me know if this it not working.

But I think its a good idea to move it to the `publishes()` method.
Thank you,

**Comment by markcameron** [comment]
Ah yes indeed I missed that part of the readme! I'll give that a shot! Thanks

**Comment by bpocallaghan** [comment]
Thank you for giving this package a shot, it seems you are the first one taking interest in this package, any feedback is welcome!

**Comment by markcameron** [comment]
Hey, I like the package, haven't had any problems. Would be nice if I could configure the add_edit view. I don't group them together in one file, but rather have the `create.blade.php` and `edit.blade.php` reference a partial that contains the form. There a chance of including something that allows for multiple custom view files from a single command? Where I could pass which stubs I want to include from the config file? like that I can add as many as I want?

**Comment by bpocallaghan** [comment]
Hi there, sorry, I've been crazy busy on other projects.
I have an idea that I want to implement. (Hopefully over the weekend)
I will let you know once I added a new version.
Thank you for the feedback.

**Comment by markcameron** [comment]
Hey,

No stress, in the mean time I've copied the ResourceCommand, and made changes to it and placed it in my Commands folder, did the same thing for a couple of other views that it uses, and it's doing the trick.

But look forward to any updates you might make!

Thanks

**Comment by bpocallaghan** [comment]
Hi there,
I've made a lot of changes, also created a new version: v2.0.0.

The main new features are:
- [config.php](https://github.com/bpocallaghan/generators/blob/master/src/config/config.php), the settings and resource_views. (in the readme, just below the main heading)
- file command, to generate your own files you want, you can create a new settings type or just new stubs, then u can generate if from this command. The settings have a bit more logic to them (path, namespace, post fix, etc
- Then the resource_views, you can split the add_edit up in there if you like, they just point to the list of subs key = value pair.
- Then also the [Available placeholders](https://github.com/bpocallaghan/generators/blob/master/resources/stubs/example.stub)

Please feel free to play around with it and let me know if I missed something or if you would like to add something else or any other ideas.
