### ISSUE TITLE
generate:migration:pivot has inverted classes

### ISSUE THREAD

**Issue by maddeezy** [bpocallaghan/generators#12]
When we use this command and inject the many to many relationship in the model, the classes are inverted.

Example

generate:migration:pivot bar foo

would currently add in the Foo Class Model

public function bars()
	{
		return $this->belongsToMany(**Foo**::class);
	}

I believe it should be

public function bars()
	{
		return $this->belongsToMany(**Bar**::class);
	}

**Comment by bpocallaghan** [comment]
Morning Morning.
Thank you for pointing it out.

I've pushed the new version (4.1.1) I think this should fix it.
I will give it a proper test later to make 100% sure (the function name was inverse as well I think)

**Comment by maddeezy** [comment]
I think that is true, but I think it may be only happening on one...I will be able to test more over the weekend.

On composer update, has the issue with the publish-stubs been fixed?  (Where the stubs are already published, but after update it looks in the vendor directory still??)

⁣Thanks, 

Erik ​

**Comment by bpocallaghan** [comment]
Commented on the [Publish Stubs Issue](https://github.com/bpocallaghan/generators/issues/11)
