### ISSUE TITLE
Trait 'Illuminate\Console\DetectsApplicationNamespace' not found in Laravel 5.3

### ISSUE THREAD

**Issue by nikkanetiya** [bpocallaghan/generators#13]
Hello,

I just noted this issue, you might be aware but still just mentioning here.

Class **ListenerCommand**, **FileCommand** which use the '**DetectsApplicationNamespace**' trait which is present only after 5.4. So please either add minimum Laravel version in a composer.json & readme.md or use **AppNamespaceDetectorTrait** for an older version.

Thanks.

**Comment by bpocallaghan** [comment]
Hi there.
Thanks for pointing it out. 
[Branch 3](https://github.com/bpocallaghan/generators/tree/3.0) is for Laravel 5.3.

But I think I should add the minimum Laravel version in composer and just document it in the readme.
I think it will also be a good idea to merge the master to branch 3, to give it the latest goodies.

Will try to get to it later today.
Sorry about this, Thanks

**Comment by nikkanetiya** [comment]
No issue, Keep up the good works.

Thanks for the package.

**Comment by maddeezy** [comment]
Definitely good work!

I tried using the default seeder class stub and created a csv from an 
existing DB...

However, the function csv_to_array is not found...is there a way to fix 
this?

**Comment by nikkanetiya** [comment]
There is no pre-built function 'csv_to_array' provided with Laravel. You can create your own.

**Comment by nikkanetiya** [comment]
@maddeezy try
 
```php
function csv_to_array($path) {
      return array_map('str_getcsv', file($path));
}
```

it might work for you, never used!!

**Comment by bpocallaghan** [comment]
Hi Guys

I've merge master to branch 3 and new release is 3.0.3.
Install with `composer require bpocallaghan/generators --dev 3`

[Branch 3 for Laravel 5.3](https://github.com/bpocallaghan/generators/tree/3.0)

Please shout if you have any questions!

**Comment by nikkanetiya** [comment]
Great. Working fine now.

**Comment by bpocallaghan** [comment]
Hi @maddeezy  . The csv_to_array function...

You can find it here. (It is part of my 'core' utility classes I have in my starter project)
[csv_to_array()](https://github.com/bpocallaghan/titan/blob/master/src/Helpers/helpers.php)

**Comment by maddeezy** [comment]
Thanks!!

Any suggestion on how to use your default csv seeder

I am getting error on csv_to_array...I created that function, but it's not working for me...do you have one that works?  (I tried the suggested solution...but it didn't parse the csv correctly)

⁣Thanks, 

Erik ​

**Comment by nikkanetiya** [comment]
@maddeezy Did you created a helper file and auto loaded in composer?

**Comment by maddeezy** [comment]
And where would I put this function so the seeder can find it?

⁣Thanks, 

Erik ​

**Comment by nikkanetiya** [comment]
@maddeezy create a file anywhere preferable in app/helpers/Helper.php and then add it in composer autoload like [this](https://github.com/bpocallaghan/titan/blob/master/composer.json#L20)

**Comment by maddeezy** [comment]
Thanks...I'll give it a try and report back.

⁣Thanks, 

Erik ​

**Comment by bpocallaghan** [comment]
@maddeezy 

I thought I share this with you [Add Helper Files](https://gist.github.com/bpocallaghan/f8b6f21e352b57a8f07f08fea2965384)

The composer.json - option 1
The HelperServiceProvider - option 2

**Comment by maddeezy** [comment]
Extremely helpful link!! Thanks...

⁣Thanks, 

Erik ​
