### ISSUE TITLE
How are shortcuts are supposed to work?

### ISSUE THREAD

**Issue by Stevemoretz** [bpocallaghan/generators#17]
Hi how do I use the shortcuts defined in the docs?

**Comment by bpocallaghan** [comment]
@Stevemoretz 
Hi Steven - do you have a Mac or Windows?
[Bash Aliases](https://laravel-news.com/bash-aliases)

**Comment by Stevemoretz** [comment]
> @Stevemoretz
> Hi Steven - do you have a Mac or Windows?
> [Bash Aliases](https://laravel-news.com/bash-aliases)

Hi thanks for the reply I have a mac

**Comment by bpocallaghan** [comment]
@Stevemoretz 
Howdy - just dropping my skype name if you are interested: `bpocallaghan`

**Comment by Stevemoretz** [comment]
> @Stevemoretz
> Howdy - just dropping my skype name if you are interested: `bpocallaghan`

Hi how you doing? I don't use Skype do you have a whatsapp or telegram account too?

**Comment by bpocallaghan** [comment]
@Stevemoretz 
Whatsapp: +264818254455
Never used Telegram :)
