### ISSUE TITLE
Migration is auto populated with personal preferences.

### ISSUE THREAD

**Issue by Stevemoretz** [bpocallaghan/generators#18]
Using this command : 

` php artisan generate:model bar --migration --plain
`

It created a migration with this up method : 

```
  public function up()
    {
        Schema::create('bars', function (Blueprint $table) {
            $table->bigIncrements('id')->unique()->index();
            
            $table->timestamps();
            $table->softDeletes();
            $table->integer('created_by')->unsigned();
            $table->integer('updated_by')->unsigned()->nullable();
            $table->integer('deleted_by')->unsigned()->nullable();
        });
    }
```
I don't want these auto generated fields from out of nowhere to come they were not in the stub file as well.

**Comment by bpocallaghan** [comment]
Hi @Stevemoretz 
You can publish the stub files and then remove them or are you saying you did this and it still added those lines even if it should not?

**Comment by Stevemoretz** [comment]
Hi @bpocallaghan 
No problem with working with stubs the problem is the stub is

```
    public function up()
    {
        {{schema_up}}
    }
```

and schema_up is added by the code of this library and it adds the fields

```
            $table->bigIncrements('id')->unique()->index();
            
            $table->timestamps();
            $table->softDeletes();
            $table->integer('created_by')->unsigned();
            $table->integer('updated_by')->unsigned()->nullable();
            $table->integer('deleted_by')->unsigned()->nullable();
```

They are not included in the stub file to change they are generated in the code in your SyntaxBuilder.php I'd suppose.

**Comment by Stevemoretz** [comment]
I debugged the code and looks like this is also using another stub in SyntaxBuilder.php so migration and schema_create.stub work with each others.

`{{schema_up}}`

has schema_create.stub in it. That's pretty cool wish it was documented though so I wouldn't have to debug to find this 👍

**Comment by bpocallaghan** [comment]
Hi @Stevemoretz 
Thanks for that. I actually forgot about that part a bit :)
Noted - let me have a looksy and add it in the readme/docs.

Please shout or feel free to PR if you want to add/change something. I will add `generate:request` soon

**Comment by Stevemoretz** [comment]
@bpocallaghan 
Why thank me!Thank you for this wonderful package 👍 
Sure I'd love to share some ideas and code if anything occurred to me I'll let you know ASAP.Can't wait to see`generate:request` as well.
