### ISSUE TITLE
PHP 8 Compat

### ISSUE THREAD

**Issue by nabeelio** [bpocallaghan/generators#22]
Hi,

It looks like this package is locked to PHP 7:

```
- bpocallaghan/generators is locked to version 7.0.1 and an update of this package was not requested.
- bpocallaghan/generators 7.0.1 requires php ^7.3 -> your php version (8.0.3) does not satisfy that requirement.
```

**Comment by bpocallaghan** [comment]
Hi @nabeelio 
I've just released a new tag that should fix this.
Please let me know if its not working for you.

Thanks for giving this package a try.

**Comment by nabeelio** [comment]
@bpocallaghan Thanks so much for the quick response!
