### ISSUE TITLE
Consistency in {{resource_name}} in Controllers

### ISSUE THREAD

**Issue by maddeezy** [bpocallaghan/generators#6]
Love the package...using it daily.

However, in using:

generate:resource example_resource

In the controller section, it is not consistent with the others like view, model, etc...

It changes the {{resource_name}} to {{resourceName}}

I commented out the code here:

private function callController()
    {
        $name = $this->getResourceControllerName();
        if ($this->confirm("Create a controller ($name) for the $this->resource resource? [yes|no]")) {
            $arg = $this->getArgumentResource();
            $name = substr_replace($arg, str_plural($this->resource), strrpos($arg, $this->resource), strlen($this->resource));
            // foo.bar_baz == foo.barBaz
            //$pieces = explode('_', $name);
            //$name = "";
            //foreach ($pieces as $k => $str) {
            //   $name .= ucfirst($str);
            //}
            $this->callCommandFile('controller', $name);
        }
    }

Now works as expected, unless I am missing why we would go fooBar instead of foo_bar when we use:
php artisan generate:resource foo_bar

Of course the model being FooBar is understandable...but when we call {{resource_name}} in the other sections...it gives foo_bar as expected.

Thanks for the hard work!

Erik

**Comment by bpocallaghan** [comment]
Hi Erik

I am glad you find the package helpful. 

Thanks for pointing out the bug. I am not really sure why I formatted it like that.
I've pushed a new release (4.0.1) Hopefully that works better :)

Please shout if you have any suggestions / questions for improvements!

Thanks!

**Comment by maddeezy** [comment]
The update fixed the issue.

Great job!
