### ISSUE TITLE
Inject methods into models during generate:migration:pivot foo bar

### ISSUE THREAD

**Issue by maddeezy** [bpocallaghan/generators#8]
Not an issue, but would be helpful.

During this process would it make sense to automatically establish the many-to-many relationship between foo and bar put 

In the Bar model:

public function foos() {
  return $this->(Belongs to many stuff here with the 4 parameters)
}

In the Foo model

public function bars(){
     return $this->belongsToMany( inverse of above not needing the 4 parameters??)
}

Thoughts?

**Comment by bpocallaghan** [comment]
Morning
Mmmm, Think it will be nice - coz you always need that.
I am just running out for a bit, will have a look when I get back.

I think the migration:pivot does not generate the Bar and Foo model - but I think it might be nice to ask a question 'Please enter the first Model to append the many-to-many relationship or 'x' to ignore?
-- user enter model name
And load the Bar file and append the code into the file -- or something like that

**Comment by maddeezy** [comment]
One more thing:

Need to add a Drop for foreign keys in the pivot table migration.

Also, the lengths of the fields in the pivot table start becoming long with the *_foreign_id and I tried in both MySQL and postgres and both failed when above 64 characters...

I know we could add a check for that in generate pivot, but that seems too late since both both pivoting models are already created.

So in generate resource, would it make sense to at least throw a "concern" is the resource_name is larger than:

_foreign_id (11 chars reserved) * 2 = 22 total reserved

64 - 22 = 42 available, so if we assume each model should not be longer than 21 characters, do not throw a "concern" and let it just pass...but if it is 21 or higher throw a "concern" stating if pivot table is used, length name may be an issue...

Thoughts?

**Comment by maddeezy** [comment]
Actually needs to check the length with _id on the model too...so really we should check if they are longer than 18...right?

Ex: model_name (10 chars)
model_name_id_foreign_id

Would pass...no concerns

However,

the_foo_barred_model_name (25 chars)
would throw the concern since if using this as a many to many relationship, the lengths of the fields in the pivot table could be too long (since we don't know what it will pivot with)

If we know we won't use a pivot, then we accept and continue to generate resource, otherwise we stop and come up with a shorter resource name

**Comment by maddeezy** [comment]
Tested this and it worked good....added in ResourceCommand.php

private function callModel()
    {
        $name = $this->getModelName();
        
        **//---------added-------------
        $resourceString = $this->getResourceOnly();
        $resourceStringLength = strlen($this->getResourceOnly());

        if ($resourceStringLength > 18) {
            $ans = $this->confirm("Your resource $resourceString may have too many characters to use for many to many relationships.  The length is $resourceStringLength.  Continue? [yes|no]");
            if ($ans === false) {
                echo "generate:resource cancelled!";
                die;
            }
        }
        //---------end of addition-------------**

        if ($this->confirm("Create a $name model? [yes|no]")) {
            $this->callCommandFile('model');
        }

**Comment by bpocallaghan** [comment]
Hi Erik

Just wanted to let you know, I have not forgotten about you.
Work got super busy all of a sudden.

Will have a look as soon as I can!

**Comment by maddeezy** [comment]
No problem...I changed locally for now.

**Comment by bpocallaghan** [comment]
Hi Erik

Thanks - I've added your code in the ResourceCommand (length validation)

I've also added in the `MigrationPivotCommand`
A confirm to add the many many relationships in the parent models.

What it will do.
`generate:migration:pivot foos bars`
Find the model `Foo` and add the `belongsToMany(Bar::class)` relationship
Find the model `Bar` and add the `belongsToMany(Foo::class)` relationship

Let me know what you think.
It should be oky for the basic relationships - I think

**Comment by maddeezy** [comment]
Thanks for adding...just a couple things:

I needed to add in the config
'many_many_relationship_stub'         => base_path() . '/vendor/bpocallaghan/generators/resources/stubs/many_many_relationship.stub',

And had to run generate:publish-stubs  (I had already done that prior to adding above, so I am not sure it was required), however, could we have an option for --force on generate:publish-stubs?  It overwrote the ones I had created, but I just cleaned them via git...

But yeah, works perfectly!  Relationships added exactly as needed in the models :)

Thanks!

**Comment by maddeezy** [comment]
On the injection into the model class, the _ is dropping

so if we migrate foo_bars users

it adds to users

public function foobars()...

I think it should be 
public function foo_bars()...

This would keep it consistent with everything else going on.

**Comment by maddeezy** [comment]
On the Remember To Add for generate:resource, when using an _ it suggests using a -

**Comment by bpocallaghan** [comment]
Morning Morning.
New releases (4.0.8)
Sorry about the missing stub in the config - Added the missing entry.
I've also added the --force for the publish-stubs command

Mmm, not really sure about the foo_bars() I personally would like it to be fooBars()?
But I do not mind adding it.
What do you think, leave it as is for now or make the function name the same as what you type to generate - $ foo_bars users, functions will be foo_bars() users() (same as the 2 table names)?

**Comment by maddeezy** [comment]
For this type of naming convention, seems as foo_bars() would be correct as we are referring to methods, where fooBars() would lead me into thinking it is a model?  Either way works for me though.  I'm liking the package more all the time :)

**Comment by bpocallaghan** [comment]
Hi
Released (4.0.9) I've used the table name as the relationship function.
Glad you like it - let me know if you think of anything to add!
Thanks

**Comment by maddeezy** [comment]
I have a few things.

In {{schema_up}}...{{resource_name}} is not pulling in and shows up as "{{resource_name}}" so if we have a resource of foo_bars...in my stub for the migration we have
$table->string('{{resource_name}}_name');

It would be nice to have it come in as
$table->string('foo_bar_name');

Validator idea...
Also, I never run the migration at the time of generate:resource since there are only a few things that are common, the rest gets built, then the migration is performed.  Once performed, it would be great to do some like:

generate:validator foo_bar

And then using Doctrine/dbal we could get the schema and inject the proper validator in the store and update of the FooBarController (at least all of the required fields.)

Thoughts?

**Comment by bpocallaghan** [comment]
Hi.
The MigrationCommand does not have access to all the 'placeholders'.

The validator is actually a very good idea!

I've created two new issues and will try to have a look at them when I can.
Please feel free to play around with the code :)

Thanks for the feedback and ideas - really appreciate it!!
