### ISSUE TITLE
Validator idea

### ISSUE THREAD

**Issue by bpocallaghan** [bpocallaghan/generators#9]
Validator idea...
Also, I never run the migration at the time of generate:resource since there are only a few things that are common, the rest gets built, then the migration is performed. Once performed, it would be great to do some like:

generate:validator foo_bar

And then using Doctrine/dbal we could get the schema and inject the proper validator in the store and update of the FooBarController (at least all of the required fields.)

**Comment by maddeezy** [comment]
Second thought...we don't need doctrine at all, just read the Laravel migration.

Then we can determine all unique, non-nullable, and number of characters, etc as defined by the migration.

**Comment by maddeezy** [comment]
Although doctrine would be better suited for apps already deployed.
